Add Docker Compose
monash-human-power/dashboard pull request #122
Opened 2021-05-30 08:42 UTC by Blake-Haydon

## Description

## Screenshots

<img width="1198" alt="Screen Shot 2021-05-29 at 3 21 43 pm" src="https://user-images.githubusercontent.com/23159604/120058947-948d2100-c091-11eb-89c1-4d819791d2bb.png">

## Steps to Test

1.

2021-05-31 12:47 UTC, hallgchris reviewed
Thanks for this! Can you add some instructions on how to use to the PR and readme?

2021-05-31 12:48 UTC, hallgchris requested changes
Thanks for this! Can you add some instructions on how to use to the PR and readme?

2021-06-12 01:17 UTC, kdav108 requested changes
From my basic understanding, this looks good, but as Chris mentioned already, it would be good to document this magical stuff.

2021-06-12 01:17 UTC, kdav108 commented on docker-compose.yml
> +        - "./.mosquitto:/mosquitto"
What does volumes represent? my quick google search wasn't clear enough for me

2021-06-12 01:17 UTC, kdav108 commented on docker-compose.yml
> +        - "1883:1883"
Is this format (`1883:1883`) a convention or does the two numbers represent different stuff?

2021-07-26 08:41 UTC, closed without merging