new branch to replace bahar-ap/rename_achieved_max_speed_topic branch
monash-human-power/dashboard pull request #135
Opened 2021-08-23 05:59 UTC by bahar-ap

## Description

this branch is used to replace the other messed-up branch (bahar-ap/rename_achieved_max_speed_topic)

## Screenshots

## Steps to Test

2021-08-23 06:20 UTC, hallgchris requested changes

2021-08-23 06:20 UTC, hallgchris commented on server/js/sockets.js
> +  mqttClient.subscribe(BOOST.prev_trap_speed);
@kdav108 Moved all these subscriptions down this file in https://github.com/monash-human-power/dashboard/pull/133, so now they're duplicated. Just need to move your new topic to where they now sit, and remove these lines

2021-08-28 09:14 UTC, kdav108 approved these changes
Works great! Nice and easy PR :)

2021-08-28 22:29 UTC, hallgchris approved these changes
Sorry for the delay, looks good!

2021-09-05 08:50 UTC, merged