Add option to flip video
monash-human-power/dashboard pull request #136
Opened 2021-08-30 08:28 UTC by bahar-ap

## Description

Adding option to flip video

## Screenshots

mosquitto_sub -t '#' -v -h localhost
OR 
mosquitto_sub -t 'camera/flip_video_feed' -v -h localhost

when clicking flip video, mqtt message should be sent :)

2021-08-31 09:03 UTC, kdav108 requested changes
Nice short PR! Nothing to complain here, just a few nit picks.

Also, it seems you've branched off from `bahar-ap/change_achieved_max_speed_name` instead of `master`, that's fine, just make sure you merge #135 first and then update this branch before merging this :)

2021-08-31 09:03 UTC, kdav108 commented on client/src/api/common/powerModel.ts
> +  const handleAchivedMaxData = useCallback((data: AchievedData) => {
I get tripped with this every time, but pretty sure the spelling was correct before, i.e. it's `Achieved`.

2021-08-31 09:03 UTC, kdav108 commented on client/src/components/common/camera_settings/OverlaySelection.tsx
> +    console.log('yes sir I got to this point');
Glad to know 😂

2021-08-31 09:03 UTC, kdav108 commented on client/src/components/common/camera_settings/OverlaySelection.tsx
> +    toast.success('Video feed is flipped!');
Maybe make this toast appear after the `emit` call, so if that errors out we don't incorrectly send a success toast message.

2021-09-05 08:49 UTC, bahar-ap commented on client/src/components/common/camera_settings/OverlaySelection.tsx
> +    console.log('yes sir I got to this point');
whoops!!! 😅

2021-09-11 01:20 UTC, kdav108 approved these changes
We're done, just really minor stuff to get rid of.

I'll approve still, we can merge after the comments below are resolved.

2021-09-11 01:20 UTC, kdav108 commented on server/js/sockets.js
> +      console.log('got to this point too sir no problem');
You forgot to remove this as well 😂

2021-09-11 01:20 UTC, kdav108 commented on client/src/components/v3/StatisticRow.tsx
> +  // eslint-disable-next-line no-unused-vars
we don't require this `ESLint-disable-next-line` stuff cos we now do use the `setPrevTrapSpeed` func. Previously we had it defined but never called it and hence we got the `no-unused-vars` error from ESLint, and had to disable it.

2021-09-11 01:20 UTC, kdav108 commented on client/src/components/v3/StatisticRow.tsx
> +  // eslint-disable-next-line no-unused-vars
Same here, should not be needed anymore

2021-09-12 02:45 UTC, hallgchris approved these changes
Nothing to add! In the future it would be great if you could include a screenshot in the PR description!

2021-09-13 04:30 UTC, merged