Make the site more responsive to different window sizes
monash-human-power/dashboard pull request #18
Opened 2019-07-26 23:27 UTC by hallgchris

- On large displays, the sidebar can be shown or hidden, and is shown by default. It does not cover page content.
- On smaller displays, the sidebar again can be shown or hidden, but is hidden by default and when opened, covers page content.
- A button in the top left toggles the sidebar, and on small displays, clicking/tapping outside the sidebar will also close it.
- On large displays, the index page now displays 2 charts on the first row and one on the next, as opposed to 3 on one row.

2019-07-28 10:10 UTC, hallgchris commented
![](https://github.trello.services/images/mini-trello-icon.png) [Better mobile experience on DAS](https://trello.com/c/4ZudBKcj/60-better-mobile-experience-on-das)

2019-07-28 13:28 UTC, khanguslee requested changes
Just a couple of small fixes from first glance.

2019-07-28 13:28 UTC, khanguslee commented on client/css/common.css
> +    background-color: #f5f5f5;
We should probably create a constants file for these colours. (No need for this PR though)

2019-07-28 13:28 UTC, khanguslee commented on client/css/common.css
> +    z-index: 10; /* in front of overlay */
I would try to steer away from `z-index` (it becomes a hassle later on if all ur elements have a z-index). Is there a reason why you have this? Or is this the *only* way we can put the element in front of the overlay?

2019-07-28 13:28 UTC, khanguslee commented on client/css/common.css
> +    z-index: 9; /* behind actual sidebar */
See above comment about stance of z-index. (Imagine having to balance 100s of these)

2019-07-28 13:28 UTC, khanguslee commented on client/partials/head.ejs
> +<link rel="stylesheet" type="text/css" href="css/bootstrap.css">
Good idea! 🎉

2019-07-28 13:28 UTC, khanguslee commented on package.json
> +    "@fortawesome/fontawesome-free": "^5.9.0",
Can you put this as a dependancy?

2019-07-28 13:28 UTC, khanguslee commented on client/js/common.js
> +/* eslint-disable no-unused-vars */
IDK how to fix this properly either, but can you use:
```
// eslint-disable-next-line no-unused-vars
```
instead? Easy one liner 😄

2019-07-28 13:31 UTC, khanguslee commented
Just had a quick demo with the test script. Looks amazing on mobile!

2019-07-28 13:33 UTC, khanguslee commented
Sidebar gets cut off on every page except for Dashboard and Download Files. pls fix.
![image](https://user-images.githubusercontent.com/18709969/62007380-11969900-b190-11e9-9110-f48e2a70ac82.png)

2019-07-29 05:15 UTC, harsilspatel commented on client/page_404.ejs
> +	  <% include ./partials/head %>
oh yeah thanks for adding this:)

2019-07-29 05:21 UTC, harsilspatel approved these changes
this looks damn cool on mobile, great work @hallgchris 🤩

2019-07-30 01:59 UTC, khanguslee approved these changes
LGTM

2019-07-30 02:02 UTC, merged