Remove use of RegExp lookbehinds
monash-human-power/dashboard pull request #27
Opened 2019-08-07 06:23 UTC by hallgchris

At this point in time, browsers other than Chrome do not support RegExp lookbehinds. This PR should make the power zone page work on browsers other than Chrome.

Test by running `mosquitto_sub -t power_model/generate_power_plan` in a console, loading the default plan on the DAShboard and submitting. I've tested on Chrome and Firefox.

2019-08-07 06:26 UTC, hallgchris commented
Another thing to note - firefox and chrome seem to be doing the "required" property of a field differently. When the forms are cleared after submitting, firefox highlights all the now empty fields. Undesirable behavior, is it worth looking into?

![image](https://user-images.githubusercontent.com/17876556/62599607-03830e00-b930-11e9-9883-2be054843f8c.png)

2019-08-07 06:28 UTC, khanguslee commented
> Another thing to note - firefox and chrome seem to be doing the "required" property of a field differently. When the forms are cleared after submitting, firefox highlights all the now empty fields. Undesirable behavior, is it worth looking into?
> 
> ![image](https://user-images.githubusercontent.com/17876556/62599607-03830e00-b930-11e9-9883-2be054843f8c.png)

Damn. I was just being lazy and didnt want to do custom validation. Maybe if you could find an easy fix?

2019-08-07 06:31 UTC, khanguslee requested changes
Cheers for this! Didn't think about testing on FF.

2019-08-07 06:31 UTC, khanguslee commented on client/js/power-zone.js
> +      inputDict[id.substring(inputPrefix.length)] = form.elements[index].value;
Maybe bring out `id.substring(inputPrefix.length)` into it's own variable to make it more clearer.

2019-08-07 08:30 UTC, hallgchris commented
> > Another thing to note - firefox and chrome seem to be doing the "required" property of a field differently. When the forms are cleared after submitting, firefox highlights all the now empty fields. Undesirable behavior, is it worth looking into?

> Damn. I was just being lazy and didnt want to do custom validation. Maybe if you could find an easy fix?

Well the easiest fix would be to make the form not reset when submit is pressed... Is this necessary, when we have a reset form button 10 times larger than the submit button?

2019-08-07 14:16 UTC, harsilspatel approved these changes
looks good to me, good work @hallgchris! :D

2019-08-09 03:25 UTC, khanguslee commented
> > > Another thing to note - firefox and chrome seem to be doing the "required" property of a field differently. When the forms are cleared after submitting, firefox highlights all the now empty fields. Undesirable behavior, is it worth looking into?
> 
> > Damn. I was just being lazy and didnt want to do custom validation. Maybe if you could find an easy fix?
> 
> Well the easiest fix would be to make the form not reset when submit is pressed... Is this necessary, when we have a reset form button 10 times larger than the submit button?

Ahh so since the submit button does not appear until the user selects number of zones, I thought the most logical place would be at the top. Looks better than having a single button up there for now. Eventually when we have more buttons, we should remove the block button.

2019-08-09 03:35 UTC, khanguslee requested changes
So close, can you figure out why we get the key `""` with value `""`?

![Screen Shot 2019-08-09 at 1 34 32 pm](https://user-images.githubusercontent.com/18709969/62752352-7fa16100-baaa-11e9-8bbd-4374c8bac637.png)

Occurs on both chrome and FF. Otherwise, code LGTM.

2019-08-12 09:13 UTC, hallgchris commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix power zone entry page on Firefox](https://trello.com/c/P1Y9QqbY/79-fix-power-zone-entry-page-on-firefox)

2019-08-12 09:37 UTC, hallgchris commented
> So close, can you figure out why we get the key `""` with value `""`?

Just fwi, this occurs on master too. But I'll look into it

2019-08-18 13:51 UTC, khanguslee commented on client/js/power-zone.js
> +    if (form.elements[index].tagName !== 'BUTTON') {
Nice find! 😮

2019-08-18 13:51 UTC, khanguslee approved these changes

2019-08-18 13:51 UTC, merged