Move prettier config file to root directory
monash-human-power/dashboard pull request #61
Opened 2020-02-23 13:46 UTC by khanguslee

## Description

Did a clean clone of the repository. VS code was incorrectly formatting the js file. By moving the `.prettierrc` file that was already in the `/server` directory, into the root directory, I was able to get vs code to autoformat the JS code using the prettier formatter.

## Screenshots

N/A

## Steps to Test

Make some changes in a file, save file whilst in vs code. VS code should format the document automatically.

2020-02-23 13:58 UTC, khanguslee commented
Seems like the code that was formatted in the repo does not represent the eslint and prettier rules we have set in the repo. We will need to discuss what we want and don't want asap.

2020-03-16 03:11 UTC, emilytrau requested changes
@khanguslee ouch my review stats!!!

2020-03-16 03:55 UTC, khanguslee commented
> @khanguslee ouch my review stats!!!

If you set WIP label it doesnt count pree sure

2020-04-17 22:41 UTC, hallgchris requested changes
Just reviewing so Pull Reminders shuts up haha

2020-08-03 23:20 UTC, hallgchris commented
@khanguslee What's the status on this?

2020-08-04 09:58 UTC, khanguslee commented
Probably a few controversial changes in here, btw. But at least we can all conform to a single style and code format.

Didn't have to change any of the existing eslint rules! Most of the changes in the files, is prettier just putting stuff in a new line etc.

LMK if you have any concerns or not. I also encourage everyone to have prettier to format your files upon saving.

2020-08-04 23:05 UTC, hallgchris submitted a review, later dismissed
Looks good to me! All things considered, our repo was quite neat already

2020-08-04 23:05 UTC, hallgchris commented on .github/workflows/linter.yml
> +          yarn eslint-check
A little weird that we have different commands for client/server

2020-08-06 07:41 UTC, khanguslee commented
> Looks good to me! All things considered, our repo was quite neat already

Yeah it already was! As we get more devs, I thought it would prevent us from reviewing code format, and start to review the contents of the code instead.

2020-08-06 13:43 UTC, hallgchris commented on server/package.json
> +    "lint:fix": "eslint --fix",
Can we have lint & fix on the client too?

2020-08-13 06:15 UTC, hallgchris approved these changes
Looks good!

2020-08-13 07:07 UTC, khanguslee commented
Just need your review now @angustrau. We can finally close this PR up!

2020-08-13 07:13 UTC, emilytrau approved these changes
Looks good to me :+1:

2020-08-13 07:14 UTC, merged