Add Docker support
monash-human-power/dashboard pull request #68
Opened 2020-07-18 06:44 UTC by angustrau

## Description

 This adds support for running the DAShboard with Docker.

## Screenshots

N/A

## Steps to Test

Follow the new setup instructions in the README.

2020-07-18 07:40 UTC, hallgchris reviewed
Noob question here - how do we connect dashboard running in a docker container to a local MQTT broker?

2020-07-18 07:42 UTC, angustrau commented
@hallgchris I added a note about this to the README section. On Linux you would use the address of the `docker0` interface instead of `localhost`

2020-07-18 08:13 UTC, hallgchris commented
Oh yeah, I gotcha. I got it to work by modifying the hardcoded address on line 85 of `sockets.js`. Did you have a neater way doing it or is that the best we have for now?

2020-07-20 09:56 UTC, hallgchris requested changes
Docker stuff looks good to me! But as discussed in the meeting yesterday, I reckon we need some way to easily connect the dashboard to a MQTT broker, cos I'd be hesitant to have the master branch require modification to make it usable whenever someone checks it out

2020-07-20 09:56 UTC, hallgchris commented on docker-compose.yml
> +    image: docker.pkg.github.com/monash-human-power/dashboard/client
What does this bit do?

2021-07-24 11:39 UTC, closed without merging